name: Publish Mod To TS

on:
  push:
    tags: "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore and Build
        run: |
          dotnet restore --locked-mode
          dotnet tool restore
          dotnet build

      - name: Publish to TS
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
          PACKAGE_VERSION: ${{ github.ref_name }}
        run: |
          dotnet publish -c Release
